FROM mysql:mysql-server

ADD docker-entrypoint-initdb.sql/ /docker-entrypoint-initdb.d/

ENV MYSQL_ROOT_PASSWORD=toor
ENV MYSQL_DATABASE=users
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=toor
ENV MYSQL_ROOT_HOST=%

CMD ["mysqld"]